# Generated by Django 4.2.4 on 2023-08-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_gamer_game_maker_game_number_of_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='type',
            new_name='game_type',
        ),
    ]
